# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_voting', models.BooleanField(verbose_name='Anonymous Voting')),
                ('multi_voting', models.BooleanField(verbose_name='Vote Multiple Times')),
                ('final_vote', models.DateTimeField(verbose_name='DateTime Vote By')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Value')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Faculty', verbose_name='Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('token', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Voter Token')),
                ('weight', models.FloatField(verbose_name='Voter Weight')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Election', verbose_name='Election')),
                ('nominee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nominee', to='vote.Faculty', verbose_name='Faculty')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Voter', to='vote.Faculty', verbose_name='Faculty')),
            ],
        ),
    ]
